### ISSUE TITLE
All sents counting towards sent limit even though they have custom limits.

### ISSUE THREAD

**Issue by storm37000** [Weol/WUMA#37]
All sents counting towards sent limit even though they have custom limits.  This hasnt happened to me personally but many people on server are reporting it with ACF and wire stuff.  It happens no matter the duplicator (vanilla or adv2) used to spawn.

**Comment by Weol** [comment]
This is odd, I will investigate

**Comment by storm37000** [comment]
just had somebody have it happen with vanilla buttons too.

**Comment by Weol** [comment]
I've found why this happens, I am working on something to mitigate this.

**Comment by Weol** [comment]
Fixed by 2f18e11f8e57f362b26932e63ab21aab8f2198b6

**Comment by storm37000** [comment]
im not running ember or darkrp, and the error is still happening on the workshop version.

**Comment by Weol** [comment]
Yes, sorry, It's not up on the workshop just yet. Will be sometime today. The commit message is a bit misleading, the fix for this problem is also in there

**Comment by Weol** [comment]
I've encountered a problem in the fix, so it is going to be delayed

**Comment by Weol** [comment]
The fix has been pushed to the workshop
